services:
  pg-db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=redis_node 
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - pgData:/var/lib/postgresql

volumes:
  pgData: